// Legal Document Generation Service
// Generates country-specific legal documents and guidance

export interface LegalContext {
  country: string;
  incidentType: string;
  victimName?: string;
  perpetratorName?: string;
  incidentDate?: string;
  description?: string;
}

// Country-specific legal frameworks
const legalFrameworks = {
  kenya: {
    name: 'Kenya',
    laws: [
      'Computer Misuse and Cybercrimes Act, 2018',
      'Sexual Offences Act, 2006',
      'Protection Against Domestic Violence Act, 2015'
    ],
    hotlines: ['1195 (GBV Hotline)', 'FIDA Kenya: +254 20 387 2131'],
    resources: [
      'FIDA Kenya - https://fidakenya.org',
      'COVAW - Coalition on Violence Against Women',
      'National Gender and Equality Commission'
    ]
  },
  nigeria: {
    name: 'Nigeria',
    laws: [
      'Violence Against Persons Prohibition Act, 2015',
      'Cybercrimes Act, 2015',
      'Criminal Code Act'
    ],
    hotlines: ['0800 ABUSE (22873)', 'National Human Rights Commission: 0800 9000 NHRC'],
    resources: [
      'Women\'s Rights Advancement and Protection Alternative (WRAPA)',
      'Project Alert on Violence Against Women',
      'Nigerian Police Force Gender Unit'
    ]
  },
  southafrica: {
    name: 'South Africa',
    laws: [
      'Domestic Violence Act, 1998',
      'Protection from Harassment Act, 2011',
      'Criminal Law (Sexual Offences and Related Matters) Amendment Act, 2007'
    ],
    hotlines: ['0800 150 150 (GBV Command Centre)', '10111 (Police)'],
    resources: [
      'Tears Foundation',
      'People Opposing Women Abuse (POWA)',
      'Commission for Gender Equality'
    ]
  },
  ghana: {
    name: 'Ghana',
    laws: [
      'Domestic Violence Act, 2007',
      'Electronic Communications Act, 2008',
      'Criminal Offences Act, 1960'
    ],
    hotlines: ['055 378 9991 (Domestic Violence Hotline)', '191 (Police)'],
    resources: [
      'Domestic Violence and Victim Support Unit (DOVVSU)',
      'Women in Law and Development in Africa (WiLDAF)',
      'Gender Centre'
    ]
  }
};

// Generate HR complaint letter
export function generateHRLetter(data: {
  victimName: string;
  companyName: string;
  perpetratorName: string;
  incidentDate: string;
  description: string;
}): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return `
${date}

To: Human Resources Department
${data.companyName}

Subject: Formal Complaint of Workplace Harassment

Dear HR Team,

I am writing to formally report an incident of workplace harassment that occurred on ${data.incidentDate}.

INCIDENT DETAILS:
- Date of Incident: ${data.incidentDate}
- Person(s) Involved: ${data.perpetratorName}
- Nature of Incident: Harassment/Gender-Based Violence

DESCRIPTION:
${data.description}

IMPACT:
This incident has created a hostile work environment and has affected my ability to perform my duties effectively. I am experiencing emotional distress and feel unsafe in the workplace.

REQUESTED ACTION:
I request that the company:
1. Conduct a thorough investigation into this matter
2. Take appropriate disciplinary action against the perpetrator
3. Implement measures to ensure my safety and prevent future incidents
4. Provide me with support resources and counseling if available

I am prepared to provide additional information and evidence as needed. I expect this matter to be handled with confidentiality and urgency.

I look forward to your prompt response and resolution of this matter.

Sincerely,
${data.victimName}

---
This letter was generated by HerCircle Shield - A GBV Support Tool
For legal advice, please consult with a qualified attorney.
`.trim();
}

// Generate police report template
export function generatePoliceReport(data: {
  country: string;
  victimName: string;
  incidentDate: string;
  location: string;
  description: string;
  evidenceList: string[];
}): string {
  const countryKey = data.country.toLowerCase() as keyof typeof legalFrameworks;
  const framework = legalFrameworks[countryKey] || legalFrameworks.kenya;
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return `
POLICE REPORT TEMPLATE
Generated: ${date}
Country: ${framework.name}

COMPLAINANT INFORMATION:
Name: ${data.victimName}
Date of Report: ${date}

INCIDENT DETAILS:
Date of Incident: ${data.incidentDate}
Location: ${data.location}
Type: Gender-Based Violence / Online Harassment

DESCRIPTION OF INCIDENT:
${data.description}

EVIDENCE AVAILABLE:
${data.evidenceList.map((item, i) => `${i + 1}. ${item}`).join('\n')}

APPLICABLE LAWS (${framework.name}):
${framework.laws.map((law: string, i: number) => `${i + 1}. ${law}`).join('\n')}

REQUESTED ACTION:
I request that the police:
1. Register this complaint formally
2. Investigate the incident thoroughly
3. Take appropriate legal action against the perpetrator
4. Provide me with a case reference number
5. Keep me informed of the investigation progress

WITNESS INFORMATION:
[To be filled by complainant if applicable]

DECLARATION:
I declare that the information provided above is true and accurate to the best of my knowledge.

Signature: ___________________
Date: ${date}

---
IMPORTANT CONTACT NUMBERS (${framework.name}):
${framework.hotlines.join('\n')}

This template was generated by HerCircle Shield.
Please review and complete all sections before submission.
`.trim();
}

// Generate cease and desist letter
export function generateCeaseAndDesist(data: {
  victimName: string;
  perpetratorName: string;
  perpetratorAddress?: string;
  description: string;
  demands: string[];
}): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return `
${date}

${data.perpetratorName}
${data.perpetratorAddress || '[Address]'}

Re: CEASE AND DESIST - Harassment and Defamation

Dear ${data.perpetratorName},

This letter serves as formal notice to CEASE AND DESIST from all harassing, threatening, and defamatory conduct directed at ${data.victimName}.

PROHIBITED CONDUCT:
${data.description}

LEGAL BASIS:
Your actions constitute harassment, cyberbullying, and potentially criminal behavior under applicable laws. These actions have caused significant emotional distress and harm to ${data.victimName}.

DEMANDS:
${data.demands.map((demand, i) => `${i + 1}. ${demand}`).join('\n')}

CONSEQUENCES OF NON-COMPLIANCE:
If you fail to comply with these demands within 7 days of receiving this letter, ${data.victimName} will pursue all available legal remedies, including but not limited to:
- Filing a police report
- Seeking a restraining order
- Pursuing civil litigation for damages
- Reporting to relevant authorities and platforms

This letter is sent without prejudice to any rights or remedies available to ${data.victimName}, all of which are expressly reserved.

Please govern yourself accordingly.

Sincerely,
${data.victimName}

---
NOTICE: This is a legal document. Keep a copy for your records.
Consider consulting with an attorney before sending.

Generated by HerCircle Shield - GBV Support Tool
`.trim();
}

// Get country-specific legal guidance
export function getLegalGuidance(country: string): any {
  const countryKey = country.toLowerCase() as keyof typeof legalFrameworks;
  const framework = legalFrameworks[countryKey] || legalFrameworks.kenya;
  
  return {
    country: framework.name,
    laws: framework.laws,
    hotlines: framework.hotlines,
    resources: framework.resources,
    steps: [
      'Document all incidents with dates, times, and evidence',
      'Save screenshots, messages, and any other proof',
      'Report to the platform where the abuse occurred',
      'Contact local authorities using the hotlines provided',
      'Seek support from local GBV organizations',
      'Consider consulting with a lawyer',
      'Prioritize your safety and well-being'
    ],
    emergencyContacts: framework.hotlines
  };
}

// Generate incident escalation wizard
export function generateEscalationPath(incidentType: string, severity: string): any {
  const paths: Record<string, Record<string, string[]>> = {
    harassment: {
      low: ['Document incident', 'Report to platform', 'Block user'],
      medium: ['Document incident', 'Report to platform', 'Contact HR/authority', 'Seek support'],
      high: ['Document incident', 'Report to platform', 'File police report', 'Get legal advice', 'Safety planning'],
      critical: ['Ensure immediate safety', 'Contact emergency services', 'File police report', 'Get protection order', 'Secure evidence']
    },
    doxxing: {
      low: ['Document leak', 'Report to platform', 'Change passwords'],
      medium: ['Document leak', 'Report to platform', 'Alert contacts', 'Monitor for misuse'],
      high: ['Document leak', 'Report to platform', 'File police report', 'Credit monitoring', 'Legal action'],
      critical: ['Ensure safety', 'Contact police', 'Get protection order', 'Relocate if needed', 'Legal action']
    },
    ncii: {
      low: ['Document content', 'Report to platform', 'Request takedown'],
      medium: ['Document content', 'Multiple platform reports', 'Hash submission', 'Support services'],
      high: ['Document content', 'Platform reports', 'Police report', 'Legal action', 'Counseling'],
      critical: ['Ensure safety', 'Emergency services', 'Police report', 'Legal action', 'Protection order', 'Crisis counseling']
    }
  };

  const path = paths[incidentType] || paths['harassment'];
  const steps = path[severity] || path['medium'];

  return {
    incidentType,
    severity,
    recommendedSteps: steps,
    urgency: severity === 'critical' ? 'IMMEDIATE' : severity === 'high' ? 'URGENT' : 'STANDARD',
    timeline: severity === 'critical' ? 'Act now' : severity === 'high' ? 'Within 24 hours' : 'Within 7 days'
  };
}
